version: '2.0'
services:
  sliconf-micro:
    build:
      context: ./
    ports:
      - 8090:8090
    container_name: sliconf-micro-container
    volumes:
      - /container/sliconf-micro:/log
      - /container/sliconf-micro/upload:/upload